/* Automatically @generated by tree-sitter v0.25.4 (726dcd1e872149d95de581589fc408fb8ea9cb0b) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_antlers_comment = 1,
  anon_sym_LBRACE_LBRACE = 2,
  anon_sym_RBRACE_RBRACE = 3,
  anon_sym_if = 4,
  anon_sym_elseif = 5,
  anon_sym_else = 6,
  anon_sym_endif = 7,
  anon_sym_SLASHif = 8,
  anon_sym_unless = 9,
  anon_sym_endunless = 10,
  anon_sym_SLASHunless = 11,
  anon_sym_COLON = 12,
  sym_variable = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_EQ_EQ = 16,
  anon_sym_BANG_EQ = 17,
  anon_sym_LT = 18,
  anon_sym_GT = 19,
  anon_sym_LT_EQ = 20,
  anon_sym_GT_EQ = 21,
  anon_sym_AMP_AMP = 22,
  anon_sym_PIPE_PIPE = 23,
  anon_sym_PLUS = 24,
  anon_sym_DASH = 25,
  anon_sym_STAR = 26,
  anon_sym_SLASH = 27,
  anon_sym_DQUOTE = 28,
  aux_sym_string_token1 = 29,
  anon_sym_SQUOTE = 30,
  aux_sym_string_token2 = 31,
  sym_number = 32,
  anon_sym_PIPE = 33,
  anon_sym_COMMA = 34,
  aux_sym_applied_modifier_token1 = 35,
  sym_text = 36,
  sym_whitespace = 37,
  sym_source = 38,
  sym__node = 39,
  sym_antlers_tag = 40,
  sym__tag_content = 41,
  sym_directive = 42,
  sym__modified_expression = 43,
  sym_expression = 44,
  sym_binary_expression = 45,
  sym_string = 46,
  sym_applied_modifier = 47,
  aux_sym_source_repeat1 = 48,
  aux_sym__modified_expression_repeat1 = 49,
  aux_sym_expression_repeat1 = 50,
  aux_sym_applied_modifier_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_antlers_comment] = "antlers_comment",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_if] = "if",
  [anon_sym_elseif] = "elseif",
  [anon_sym_else] = "else",
  [anon_sym_endif] = "endif",
  [anon_sym_SLASHif] = "/if",
  [anon_sym_unless] = "unless",
  [anon_sym_endunless] = "endunless",
  [anon_sym_SLASHunless] = "/unless",
  [anon_sym_COLON] = ":",
  [sym_variable] = "variable",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [sym_number] = "number",
  [anon_sym_PIPE] = "|",
  [anon_sym_COMMA] = ",",
  [aux_sym_applied_modifier_token1] = "applied_modifier_token1",
  [sym_text] = "text",
  [sym_whitespace] = "whitespace",
  [sym_source] = "source",
  [sym__node] = "_node",
  [sym_antlers_tag] = "antlers_tag",
  [sym__tag_content] = "_tag_content",
  [sym_directive] = "directive",
  [sym__modified_expression] = "_modified_expression",
  [sym_expression] = "expression",
  [sym_binary_expression] = "binary_expression",
  [sym_string] = "string",
  [sym_applied_modifier] = "applied_modifier",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym__modified_expression_repeat1] = "_modified_expression_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_applied_modifier_repeat1] = "applied_modifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_antlers_comment] = sym_antlers_comment,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_endif] = anon_sym_endif,
  [anon_sym_SLASHif] = anon_sym_SLASHif,
  [anon_sym_unless] = anon_sym_unless,
  [anon_sym_endunless] = anon_sym_endunless,
  [anon_sym_SLASHunless] = anon_sym_SLASHunless,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_variable] = sym_variable,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_number] = sym_number,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_applied_modifier_token1] = aux_sym_applied_modifier_token1,
  [sym_text] = sym_text,
  [sym_whitespace] = sym_whitespace,
  [sym_source] = sym_source,
  [sym__node] = sym__node,
  [sym_antlers_tag] = sym_antlers_tag,
  [sym__tag_content] = sym__tag_content,
  [sym_directive] = sym_directive,
  [sym__modified_expression] = sym__modified_expression,
  [sym_expression] = sym_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_string] = sym_string,
  [sym_applied_modifier] = sym_applied_modifier,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym__modified_expression_repeat1] = aux_sym__modified_expression_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_applied_modifier_repeat1] = aux_sym_applied_modifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_antlers_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASHif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endunless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASHunless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_applied_modifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_antlers_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__tag_content] = {
    .visible = false,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__modified_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_applied_modifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__modified_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_applied_modifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '!', 22,
        '"', 96,
        '&', 10,
        '\'', 120,
        '(', 81,
        ')', 82,
        '*', 93,
        '+', 91,
        ',', 148,
        '-', 92,
        '/', 95,
        ':', 61,
        '<', 85,
        '=', 23,
        '>', 86,
        'e', 70,
        'i', 66,
        'u', 73,
        '{', 31,
        '|', 147,
        '}', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(150);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(15);
      if (lookahead == '#') ADVANCE(9);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 96,
        '\'', 120,
        '(', 81,
        ')', 82,
        ',', 148,
        '/', 26,
        ':', 61,
        'e', 70,
        'i', 66,
        'u', 73,
        '{', 32,
        '|', 146,
        '}', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(150);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(96);
      if (lookahead == '\'') ADVANCE(120);
      if (lookahead == '(') ADVANCE(81);
      if (lookahead == '{') ADVANCE(32);
      if (lookahead == '}') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(150);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '}') ADVANCE(45);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '}') ADVANCE(4);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '}') ADVANCE(7);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '}') ADVANCE(9);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '&') ADVANCE(89);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(13);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == '-') ADVANCE(18);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == '-') ADVANCE(11);
      END_STATE();
    case 16:
      if (lookahead == '-') ADVANCE(12);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '-') ADVANCE(37);
      END_STATE();
    case 18:
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '}') ADVANCE(36);
      END_STATE();
    case 19:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '}') ADVANCE(48);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '-') ADVANCE(14);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 22:
      if (lookahead == '=') ADVANCE(84);
      END_STATE();
    case 23:
      if (lookahead == '=') ADVANCE(83);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 25:
      if (lookahead == 'f') ADVANCE(57);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(25);
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 31:
      if (lookahead == '{') ADVANCE(51);
      END_STATE();
    case 32:
      if (lookahead == '{') ADVANCE(1);
      END_STATE();
    case 33:
      if (lookahead == '{') ADVANCE(32);
      if (lookahead == '|') ADVANCE(146);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(149);
      END_STATE();
    case 34:
      if (lookahead == '|') ADVANCE(90);
      END_STATE();
    case 35:
      if (lookahead == '}') ADVANCE(52);
      END_STATE();
    case 36:
      if (lookahead == '}') ADVANCE(42);
      END_STATE();
    case 37:
      if (lookahead == '}') ADVANCE(36);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(145);
      END_STATE();
    case 39:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '!', 22,
        '"', 96,
        '&', 10,
        '\'', 120,
        '(', 81,
        ')', 82,
        '*', 93,
        '+', 91,
        '-', 92,
        '/', 94,
        '<', 85,
        '=', 23,
        '>', 86,
        '{', 32,
        '|', 34,
        '}', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(149);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      if (lookahead == '{') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(151);
      if (lookahead != 0) ADVANCE(152);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_antlers_comment);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_antlers_comment);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '-') ADVANCE(114);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_antlers_comment);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '#') ADVANCE(101);
      if (lookahead == '}') ADVANCE(110);
      if (lookahead != 0) ADVANCE(110);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_antlers_comment);
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '}') ADVANCE(7);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_antlers_comment);
      if (lookahead == '#') ADVANCE(123);
      if (lookahead == '\'') ADVANCE(7);
      if (lookahead == '}') ADVANCE(126);
      if (lookahead != 0) ADVANCE(126);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_antlers_comment);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '-') ADVANCE(138);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_antlers_comment);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_antlers_comment);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(119);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_antlers_comment);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(143);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '!') ADVANCE(15);
      if (lookahead == '#') ADVANCE(9);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_elseif);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == 'i') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_endif);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SLASHif);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_unless);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_endunless);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_SLASHunless);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'd') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'f') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'f') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'f') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'i') ADVANCE(67);
      if (lookahead == 'u') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'l') ADVANCE(75);
      if (lookahead == 'n') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'l') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'l') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'n') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'n') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 's') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 's') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 's') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 's') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 's') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(88);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == 'i') ADVANCE(25);
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '!') ADVANCE(112);
      if (lookahead == '#') ADVANCE(98);
      if (lookahead != 0 &&
          (lookahead < '!' || '#' < lookahead)) ADVANCE(119);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '#') ADVANCE(109);
      if (lookahead == '}') ADVANCE(98);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(16);
      if (lookahead == '-') ADVANCE(106);
      if (lookahead != 0) ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '#') ADVANCE(101);
      if (lookahead == '}') ADVANCE(119);
      if (lookahead != 0) ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '#') ADVANCE(101);
      if (lookahead == '}') ADVANCE(118);
      if (lookahead != 0) ADVANCE(100);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '-') ADVANCE(113);
      if (lookahead == '}') ADVANCE(104);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '-') ADVANCE(113);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '-') ADVANCE(114);
      if (lookahead == '}') ADVANCE(43);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '-') ADVANCE(114);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '-') ADVANCE(102);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '-') ADVANCE(103);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '#') ADVANCE(101);
      if (lookahead == '}') ADVANCE(44);
      if (lookahead != 0) ADVANCE(110);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '#') ADVANCE(101);
      if (lookahead == '}') ADVANCE(108);
      if (lookahead != 0) ADVANCE(110);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '#') ADVANCE(101);
      if (lookahead == '}') ADVANCE(110);
      if (lookahead != 0) ADVANCE(110);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(119);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(119);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(117);
      if (lookahead == '}') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(119);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(119);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '{') ADVANCE(116);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(119);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '{') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(119);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '}') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(119);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '}') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(119);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(119);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '!') ADVANCE(136);
      if (lookahead == '#') ADVANCE(127);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(143);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '#') ADVANCE(123);
      if (lookahead == '\'') ADVANCE(8);
      if (lookahead == '}') ADVANCE(143);
      if (lookahead != 0) ADVANCE(122);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '#') ADVANCE(123);
      if (lookahead == '\'') ADVANCE(8);
      if (lookahead == '}') ADVANCE(142);
      if (lookahead != 0) ADVANCE(122);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '#') ADVANCE(123);
      if (lookahead == '\'') ADVANCE(7);
      if (lookahead == '}') ADVANCE(46);
      if (lookahead != 0) ADVANCE(126);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '#') ADVANCE(123);
      if (lookahead == '\'') ADVANCE(7);
      if (lookahead == '}') ADVANCE(124);
      if (lookahead != 0) ADVANCE(126);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '#') ADVANCE(123);
      if (lookahead == '\'') ADVANCE(7);
      if (lookahead == '}') ADVANCE(126);
      if (lookahead != 0) ADVANCE(126);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '#') ADVANCE(125);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '}') ADVANCE(127);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\'') ADVANCE(16);
      if (lookahead == '-') ADVANCE(133);
      if (lookahead != 0) ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '-') ADVANCE(137);
      if (lookahead == '}') ADVANCE(131);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '-') ADVANCE(137);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '-') ADVANCE(138);
      if (lookahead == '}') ADVANCE(47);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '-') ADVANCE(138);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '-') ADVANCE(129);
      if (lookahead != 0) ADVANCE(134);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '-') ADVANCE(130);
      if (lookahead != 0) ADVANCE(134);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '-') ADVANCE(128);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(143);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '-') ADVANCE(135);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(143);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '-') ADVANCE(141);
      if (lookahead == '}') ADVANCE(142);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(143);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '-') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(143);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '{') ADVANCE(140);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(143);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '{') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(143);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '}') ADVANCE(142);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(143);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '}') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(143);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(143);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(145);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(90);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(aux_sym_applied_modifier_token1);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_applied_modifier_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(153);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_applied_modifier_token1);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(152);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(152);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_whitespace);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(153);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 40},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 39},
  [5] = {.lex_state = 39},
  [6] = {.lex_state = 39},
  [7] = {.lex_state = 39},
  [8] = {.lex_state = 39},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 39},
  [15] = {.lex_state = 39},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 39},
  [18] = {.lex_state = 39},
  [19] = {.lex_state = 39},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 39},
  [22] = {.lex_state = 39},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 40},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 40},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 40},
  [60] = {.lex_state = 40},
  [61] = {.lex_state = 40},
  [62] = {.lex_state = 40},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 33},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 39},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 39},
  [77] = {.lex_state = 39},
  [78] = {.lex_state = 39},
  [79] = {.lex_state = 39},
  [80] = {.lex_state = 39},
  [81] = {.lex_state = 39},
  [82] = {.lex_state = 115},
  [83] = {.lex_state = 139},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_antlers_comment] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [anon_sym_SLASHif] = ACTIONS(1),
    [anon_sym_unless] = ACTIONS(1),
    [anon_sym_endunless] = ACTIONS(1),
    [anon_sym_SLASHunless] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_applied_modifier_token1] = ACTIONS(5),
    [sym_whitespace] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(81),
    [sym__node] = STATE(29),
    [sym_antlers_tag] = STATE(29),
    [aux_sym_source_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_antlers_comment] = ACTIONS(9),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(11),
    [aux_sym_applied_modifier_token1] = ACTIONS(5),
    [sym_text] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(15), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(23), 1,
      sym_variable,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      sym_number,
    ACTIONS(33), 1,
      sym_whitespace,
    STATE(47), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_SLASHif,
      anon_sym_SLASHunless,
    STATE(52), 2,
      sym_binary_expression,
      sym_string,
    ACTIONS(17), 3,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_unless,
    ACTIONS(19), 3,
      anon_sym_else,
      anon_sym_endif,
      anon_sym_endunless,
    STATE(69), 3,
      sym__tag_content,
      sym_directive,
      sym__modified_expression,
  [54] = 15,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(23), 1,
      sym_variable,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(37), 1,
      sym_whitespace,
    STATE(44), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_SLASHif,
      anon_sym_SLASHunless,
    STATE(52), 2,
      sym_binary_expression,
      sym_string,
    ACTIONS(17), 3,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_unless,
    ACTIONS(19), 3,
      anon_sym_else,
      anon_sym_endif,
      anon_sym_endunless,
    STATE(72), 3,
      sym__tag_content,
      sym_directive,
      sym__modified_expression,
  [108] = 4,
    ACTIONS(39), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 10,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [132] = 4,
    ACTIONS(45), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 10,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [156] = 4,
    ACTIONS(47), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 10,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [180] = 4,
    ACTIONS(49), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 10,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [204] = 3,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 10,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [225] = 11,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      sym_number,
    ACTIONS(51), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(53), 1,
      sym_variable,
    ACTIONS(55), 1,
      sym_whitespace,
    STATE(64), 1,
      sym_expression,
    STATE(52), 2,
      sym_binary_expression,
      sym_string,
  [260] = 11,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      sym_number,
    ACTIONS(53), 1,
      sym_variable,
    ACTIONS(58), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(60), 1,
      sym_whitespace,
    STATE(67), 1,
      sym_expression,
    STATE(52), 2,
      sym_binary_expression,
      sym_string,
  [295] = 10,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      sym_number,
    ACTIONS(53), 1,
      sym_variable,
    ACTIONS(62), 1,
      sym_whitespace,
    STATE(70), 1,
      sym_expression,
    STATE(52), 2,
      sym_binary_expression,
      sym_string,
  [327] = 11,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      sym_variable,
    ACTIONS(66), 1,
      sym_number,
    ACTIONS(68), 1,
      sym_whitespace,
    STATE(34), 1,
      sym_string,
    STATE(35), 1,
      sym_expression,
    STATE(52), 1,
      sym_binary_expression,
  [361] = 11,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(70), 1,
      sym_variable,
    ACTIONS(72), 1,
      sym_number,
    ACTIONS(74), 1,
      sym_whitespace,
    STATE(38), 1,
      sym_string,
    STATE(39), 1,
      sym_expression,
    STATE(52), 1,
      sym_binary_expression,
  [395] = 8,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      sym_number,
    ACTIONS(53), 1,
      sym_variable,
    STATE(63), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
    STATE(52), 2,
      sym_binary_expression,
      sym_string,
  [422] = 8,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      sym_number,
    ACTIONS(53), 1,
      sym_variable,
    STATE(71), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
    STATE(52), 2,
      sym_binary_expression,
      sym_string,
  [449] = 8,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      sym_whitespace,
    STATE(37), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(76), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
    STATE(25), 2,
      sym_applied_modifier,
      aux_sym_expression_repeat1,
  [476] = 9,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(70), 1,
      sym_variable,
    ACTIONS(72), 1,
      sym_number,
    STATE(38), 1,
      sym_string,
    STATE(39), 1,
      sym_expression,
    STATE(52), 1,
      sym_binary_expression,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
  [505] = 8,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      sym_number,
    ACTIONS(53), 1,
      sym_variable,
    STATE(51), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
    STATE(52), 2,
      sym_binary_expression,
      sym_string,
  [532] = 10,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(85), 1,
      sym_variable,
    ACTIONS(87), 1,
      sym_number,
    ACTIONS(89), 1,
      aux_sym_applied_modifier_token1,
    STATE(52), 1,
      sym_binary_expression,
    STATE(54), 1,
      sym_expression,
    STATE(56), 1,
      sym_string,
  [563] = 8,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      sym_whitespace,
    STATE(41), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(91), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
    STATE(25), 2,
      sym_applied_modifier,
      aux_sym_expression_repeat1,
  [590] = 9,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(94), 1,
      sym_variable,
    ACTIONS(96), 1,
      sym_number,
    STATE(42), 1,
      sym_string,
    STATE(43), 1,
      sym_expression,
    STATE(52), 1,
      sym_binary_expression,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
  [619] = 9,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(98), 1,
      sym_variable,
    ACTIONS(100), 1,
      sym_number,
    STATE(52), 1,
      sym_binary_expression,
    STATE(57), 1,
      sym_string,
    STATE(58), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
  [648] = 8,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      sym_whitespace,
    STATE(30), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(102), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
    STATE(25), 2,
      sym_applied_modifier,
      aux_sym_expression_repeat1,
  [675] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    ACTIONS(83), 1,
      sym_whitespace,
    STATE(25), 2,
      sym_applied_modifier,
      aux_sym_expression_repeat1,
    ACTIONS(105), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [697] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    ACTIONS(83), 1,
      sym_whitespace,
    STATE(26), 2,
      sym_applied_modifier,
      aux_sym_expression_repeat1,
    ACTIONS(107), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [719] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(111), 1,
      anon_sym_PIPE,
    ACTIONS(114), 1,
      sym_whitespace,
    STATE(26), 2,
      sym_applied_modifier,
      aux_sym_expression_repeat1,
    ACTIONS(109), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [741] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(120), 1,
      anon_sym_PIPE,
    ACTIONS(124), 1,
      sym_whitespace,
    STATE(25), 2,
      sym_applied_modifier,
      aux_sym_expression_repeat1,
    ACTIONS(117), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [763] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(131), 1,
      anon_sym_PIPE,
    ACTIONS(135), 1,
      sym_whitespace,
    STATE(25), 2,
      sym_applied_modifier,
      aux_sym_expression_repeat1,
    ACTIONS(128), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [785] = 6,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 1,
      sym_antlers_comment,
    ACTIONS(143), 1,
      sym_text,
    STATE(32), 3,
      sym__node,
      sym_antlers_tag,
      aux_sym_source_repeat1,
  [806] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      sym_whitespace,
    STATE(40), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(145), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [827] = 5,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(151), 1,
      anon_sym_COLON,
    ACTIONS(153), 1,
      sym_whitespace,
    ACTIONS(149), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [846] = 6,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
    ACTIONS(157), 1,
      sym_antlers_comment,
    ACTIONS(160), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(163), 1,
      sym_text,
    STATE(32), 3,
      sym__node,
      sym_antlers_tag,
      aux_sym_source_repeat1,
  [867] = 5,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(168), 1,
      anon_sym_COLON,
    ACTIONS(170), 1,
      sym_whitespace,
    ACTIONS(166), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [886] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(172), 1,
      sym_whitespace,
    STATE(37), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(76), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [907] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      sym_whitespace,
    STATE(37), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(175), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [928] = 7,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    ACTIONS(83), 1,
      sym_whitespace,
    ACTIONS(105), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(179), 1,
      anon_sym_COLON,
    STATE(25), 2,
      sym_applied_modifier,
      aux_sym_expression_repeat1,
  [951] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      sym_whitespace,
    STATE(40), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(181), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [972] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      sym_whitespace,
    STATE(41), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(91), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [993] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      sym_whitespace,
    STATE(41), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(181), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1014] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      sym_whitespace,
    STATE(40), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(188), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1035] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(197), 1,
      sym_whitespace,
    STATE(40), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(195), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1056] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      sym_whitespace,
    STATE(30), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(102), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1077] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      sym_whitespace,
    STATE(30), 1,
      aux_sym_applied_modifier_repeat1,
    ACTIONS(195), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1098] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(45), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    ACTIONS(202), 1,
      sym_whitespace,
    STATE(48), 2,
      sym_applied_modifier,
      aux_sym__modified_expression_repeat1,
  [1118] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(204), 1,
      sym_whitespace,
    ACTIONS(109), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1134] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(206), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(208), 1,
      anon_sym_PIPE,
    ACTIONS(211), 1,
      sym_whitespace,
    STATE(46), 2,
      sym_applied_modifier,
      aux_sym__modified_expression_repeat1,
  [1154] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(35), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    ACTIONS(213), 1,
      sym_whitespace,
    STATE(48), 2,
      sym_applied_modifier,
      aux_sym__modified_expression_repeat1,
  [1174] = 6,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    ACTIONS(215), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(217), 1,
      sym_whitespace,
    STATE(46), 2,
      sym_applied_modifier,
      aux_sym__modified_expression_repeat1,
  [1194] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(221), 1,
      sym_whitespace,
    ACTIONS(219), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1210] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(225), 1,
      sym_whitespace,
    ACTIONS(223), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1226] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(229), 1,
      sym_whitespace,
    ACTIONS(227), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1242] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(231), 1,
      sym_whitespace,
    ACTIONS(105), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1258] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(235), 1,
      sym_whitespace,
    ACTIONS(233), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1274] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(237), 1,
      sym_whitespace,
    ACTIONS(188), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1290] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(242), 1,
      sym_whitespace,
    ACTIONS(240), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1306] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(244), 1,
      sym_whitespace,
    ACTIONS(117), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1322] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(247), 1,
      sym_whitespace,
    ACTIONS(128), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1338] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(252), 1,
      sym_whitespace,
    ACTIONS(250), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1354] = 3,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(255), 2,
      ts_builtin_sym_end,
      sym_antlers_comment,
    ACTIONS(257), 2,
      anon_sym_LBRACE_LBRACE,
      sym_text,
  [1366] = 3,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(259), 2,
      ts_builtin_sym_end,
      sym_antlers_comment,
    ACTIONS(261), 2,
      anon_sym_LBRACE_LBRACE,
      sym_text,
  [1378] = 3,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(263), 2,
      ts_builtin_sym_end,
      sym_antlers_comment,
    ACTIONS(265), 2,
      anon_sym_LBRACE_LBRACE,
      sym_text,
  [1390] = 3,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(267), 2,
      ts_builtin_sym_end,
      sym_antlers_comment,
    ACTIONS(269), 2,
      anon_sym_LBRACE_LBRACE,
      sym_text,
  [1402] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(51), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(177), 1,
      sym_whitespace,
  [1415] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(58), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(177), 1,
      sym_whitespace,
  [1428] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(271), 1,
      sym_variable,
    ACTIONS(273), 1,
      sym_whitespace,
  [1441] = 3,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    STATE(45), 1,
      sym_applied_modifier,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
  [1452] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(177), 1,
      sym_whitespace,
    ACTIONS(275), 1,
      anon_sym_RBRACE_RBRACE,
  [1465] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(277), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(279), 1,
      sym_whitespace,
  [1478] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(35), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(37), 1,
      sym_whitespace,
  [1491] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
    ACTIONS(283), 1,
      sym_whitespace,
  [1504] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(39), 1,
      anon_sym_RPAREN,
    ACTIONS(285), 1,
      sym_whitespace,
  [1517] = 4,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(45), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(287), 1,
      sym_whitespace,
  [1530] = 2,
    ACTIONS(289), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
  [1538] = 3,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(291), 1,
      sym_whitespace,
  [1548] = 3,
    ACTIONS(3), 1,
      sym_antlers_comment,
    ACTIONS(5), 1,
      aux_sym_applied_modifier_token1,
    ACTIONS(293), 1,
      sym_whitespace,
  [1558] = 2,
    ACTIONS(295), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
  [1566] = 2,
    ACTIONS(45), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
  [1574] = 2,
    ACTIONS(297), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
  [1582] = 2,
    ACTIONS(47), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
  [1590] = 2,
    ACTIONS(297), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
  [1598] = 2,
    ACTIONS(299), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
  [1606] = 2,
    ACTIONS(301), 1,
      aux_sym_string_token1,
    ACTIONS(5), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
  [1614] = 2,
    ACTIONS(303), 1,
      aux_sym_string_token2,
    ACTIONS(5), 2,
      sym_antlers_comment,
      aux_sym_applied_modifier_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 156,
  [SMALL_STATE(7)] = 180,
  [SMALL_STATE(8)] = 204,
  [SMALL_STATE(9)] = 225,
  [SMALL_STATE(10)] = 260,
  [SMALL_STATE(11)] = 295,
  [SMALL_STATE(12)] = 327,
  [SMALL_STATE(13)] = 361,
  [SMALL_STATE(14)] = 395,
  [SMALL_STATE(15)] = 422,
  [SMALL_STATE(16)] = 449,
  [SMALL_STATE(17)] = 476,
  [SMALL_STATE(18)] = 505,
  [SMALL_STATE(19)] = 532,
  [SMALL_STATE(20)] = 563,
  [SMALL_STATE(21)] = 590,
  [SMALL_STATE(22)] = 619,
  [SMALL_STATE(23)] = 648,
  [SMALL_STATE(24)] = 675,
  [SMALL_STATE(25)] = 697,
  [SMALL_STATE(26)] = 719,
  [SMALL_STATE(27)] = 741,
  [SMALL_STATE(28)] = 763,
  [SMALL_STATE(29)] = 785,
  [SMALL_STATE(30)] = 806,
  [SMALL_STATE(31)] = 827,
  [SMALL_STATE(32)] = 846,
  [SMALL_STATE(33)] = 867,
  [SMALL_STATE(34)] = 886,
  [SMALL_STATE(35)] = 907,
  [SMALL_STATE(36)] = 928,
  [SMALL_STATE(37)] = 951,
  [SMALL_STATE(38)] = 972,
  [SMALL_STATE(39)] = 993,
  [SMALL_STATE(40)] = 1014,
  [SMALL_STATE(41)] = 1035,
  [SMALL_STATE(42)] = 1056,
  [SMALL_STATE(43)] = 1077,
  [SMALL_STATE(44)] = 1098,
  [SMALL_STATE(45)] = 1118,
  [SMALL_STATE(46)] = 1134,
  [SMALL_STATE(47)] = 1154,
  [SMALL_STATE(48)] = 1174,
  [SMALL_STATE(49)] = 1194,
  [SMALL_STATE(50)] = 1210,
  [SMALL_STATE(51)] = 1226,
  [SMALL_STATE(52)] = 1242,
  [SMALL_STATE(53)] = 1258,
  [SMALL_STATE(54)] = 1274,
  [SMALL_STATE(55)] = 1290,
  [SMALL_STATE(56)] = 1306,
  [SMALL_STATE(57)] = 1322,
  [SMALL_STATE(58)] = 1338,
  [SMALL_STATE(59)] = 1354,
  [SMALL_STATE(60)] = 1366,
  [SMALL_STATE(61)] = 1378,
  [SMALL_STATE(62)] = 1390,
  [SMALL_STATE(63)] = 1402,
  [SMALL_STATE(64)] = 1415,
  [SMALL_STATE(65)] = 1428,
  [SMALL_STATE(66)] = 1441,
  [SMALL_STATE(67)] = 1452,
  [SMALL_STATE(68)] = 1465,
  [SMALL_STATE(69)] = 1478,
  [SMALL_STATE(70)] = 1491,
  [SMALL_STATE(71)] = 1504,
  [SMALL_STATE(72)] = 1517,
  [SMALL_STATE(73)] = 1530,
  [SMALL_STATE(74)] = 1538,
  [SMALL_STATE(75)] = 1548,
  [SMALL_STATE(76)] = 1558,
  [SMALL_STATE(77)] = 1566,
  [SMALL_STATE(78)] = 1574,
  [SMALL_STATE(79)] = 1582,
  [SMALL_STATE(80)] = 1590,
  [SMALL_STATE(81)] = 1598,
  [SMALL_STATE(82)] = 1606,
  [SMALL_STATE(83)] = 1614,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_directive, 3, 0, 0), SHIFT(10),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 4, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 4, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(sym_applied_modifier, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(sym_applied_modifier, 5, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(sym_applied_modifier, 6, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(aux_sym_applied_modifier_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 3, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(aux_sym_applied_modifier_repeat1, 2, 0, 0), SHIFT(65),
  [124] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(aux_sym_applied_modifier_repeat1, 2, 0, 0), SHIFT(66),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(aux_sym_applied_modifier_repeat1, 3, 0, 0),
  [131] = {.entry = {.count = 3, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(aux_sym_applied_modifier_repeat1, 3, 0, 0), SHIFT(65),
  [135] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(aux_sym_applied_modifier_repeat1, 3, 0, 0), SHIFT(66),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_applied_modifier, 7, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_applied_modifier, 7, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_applied_modifier, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_applied_modifier, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [160] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_applied_modifier, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_applied_modifier, 3, 0, 0),
  [172] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(sym_applied_modifier, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_applied_modifier, 4, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_applied_modifier, 5, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_applied_modifier, 5, 0, 0),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(sym_applied_modifier, 5, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_applied_modifier_repeat1, 2, 0, 0),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_applied_modifier_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_applied_modifier_repeat1, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_applied_modifier, 6, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_applied_modifier, 6, 0, 0),
  [199] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(sym_applied_modifier, 6, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__modified_expression_repeat1, 2, 0, 0),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__modified_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__modified_expression_repeat1, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__modified_expression, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__modified_expression, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 4, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 5, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 5, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 5, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 5, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [237] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_applied_modifier_repeat1, 2, 0, 0), SHIFT(8),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [244] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(aux_sym_applied_modifier_repeat1, 2, 0, 0),
  [247] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0), REDUCE(aux_sym_applied_modifier_repeat1, 3, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_applied_modifier_repeat1, 3, 0, 0),
  [252] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_applied_modifier_repeat1, 3, 0, 0), SHIFT(8),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_antlers_tag, 5, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_antlers_tag, 5, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_antlers_tag, 3, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_antlers_tag, 3, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_antlers_tag, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_antlers_tag, 2, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_antlers_tag, 4, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_antlers_tag, 4, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 5, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 1, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [287] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [291] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [293] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [299] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [303] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_antlers(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "antlers",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
